### ISSUE TITLE
Example prometheus dashboard?

### ISSUE THREAD

**Issue by fmotrifork** [ncarlier/apimon#1]
Hi, 

Great tool to have for the toolbox. :+1: 

Is it possible to add the Json for creating the example prometheus dashboard to the repo? Or publish it on grafana.com?

Thanks!

**Comment by ncarlier** [comment]
Hi,

my apologies for this late response. I just pushed a new release that improve a bit the Prometheus writer. You can find a dashboard example here: https://github.com/ncarlier/apimon/tree/master/dashboard

Regards

**Comment by fmotrifork** [comment]
Very cool! Thanks a lot!
